<html>
<title>Beyond try/catch</title>
</head>
<body>
<p>
<a href="https://github.com/laforge49/JActor2#readme">JActor2</a> &gt; <a href="../../index.html">Docs</a> &gt; <a href="../index.html">Tutorials</a> &gt; <a href="index.html">Core</a> &gt; ExceptionHandler
</p>
<h1>ExceptionHandler - Beyond try/catch</h1>
<p>
The try/catch clause provides a way to catch exceptions,
but it does not work so well with send.
The reason is that the scope of a try/catch clause is determined by control flow, rather than data flow.
So there is no way to catch an exception that was raised while processing a request on another thread.
But this is covered through the use of an 
<a href="../../api/core/org/agilewiki/jactor2/core/requests/ExceptionHandler.html">ExceptionHandler</a>.
</p>
<p>
An ExceptionHandler can be assigned while processing a asynchronous request by calling the
<a href="../../api/core/org/agilewiki/jactor2/core/requests/impl/AsyncRequestImpl.html#setExceptionHandler-org.agilewiki.jactor2.core.requests.ExceptionHandler-">setExceptionHandler</a> 
method.
This is illustrated by the <a href="java7/ExceptionHandlerSample.java">ExceptionHandlerSample</a> program.
</p>
<pre>
import org.agilewiki.jactor2.core.blades.NonBlockingBladeBase;
import org.agilewiki.jactor2.core.impl.Plant;
import org.agilewiki.jactor2.core.requests.AOp;
import org.agilewiki.jactor2.core.requests.AsyncResponseProcessor;
import org.agilewiki.jactor2.core.requests.ExceptionHandler;
import org.agilewiki.jactor2.core.requests.impl.AsyncRequestImpl;

import java.io.IOException;

public class ExceptionHandlerSample {

    public static void main(final String[] _args) throws Exception {

        //A facility with two threads.
        new Plant(2);

        try {

            //Create an ExceptionBlade.
            ExceptionBlade exceptionBlade = new ExceptionBlade();

            try {
                //Create and call an exception request.
                exceptionBlade.exceptionAOp().call();
                System.out.println("can not get here");
            } catch (IOException ise) {
                System.out.println("got first IOException, as expected");
            }

            //Create an ExceptionHandlerBlade.
            ExceptionHandlerBlade exceptionHandlerBlade =
                    new ExceptionHandlerBlade(exceptionBlade);
            //Create a test request, call it and print the results.
            System.out.println(exceptionHandlerBlade.testAOp().call());

        } finally {
            //shutdown the facility
            Plant.close();
        }
    }
}

//A blade with a request that throws an exception.
class ExceptionBlade extends NonBlockingBladeBase {
	ExceptionBlade() throws Exception {
	}

    //Returns an exception request.
    AOp&lt;Void&gt; exceptionAOp() {
        return new AOp&lt;Void&gt;("exception", getReactor()) {
            @Override
            protected void processAsyncOperation(final AsyncRequestImpl _asyncRequestImpl, 
					final AsyncResponseProcessor&lt;Void&gt; _asyncResponseProcessor) throws Exception {
                throw new IOException(); //Throw an exception when the request is processed.
            }
        };
    }
}

//A blade with an exception handler.
class ExceptionHandlerBlade extends NonBlockingBladeBase {

    //A blade with a request that throws an exception.
    private final ExceptionBlade exceptionBlade;

    //Create an exception handler blade with a reference to an exception blade.
    ExceptionHandlerBlade(final ExceptionBlade _exceptionBlade) throws Exception {
        exceptionBlade = _exceptionBlade;
    }

    //Returns a test request.
    AOp&lt;String&gt; testAOp() {
        return new AOp&lt;String&gt;("test", getReactor()) {
            @Override
            protected void processAsyncOperation(final AsyncRequestImpl _asyncRequestImpl, 
					final AsyncResponseProcessor&lt;String&gt; _asyncResponseProcessor) throws Exception {
 
                //Create and assign an exception handler.
                _asyncRequestImpl.setExceptionHandler(new ExceptionHandler&lt;String&gt;() {
                    @Override
                    public String processException(final Exception _exception) throws Exception {
                        if (_exception instanceof IOException) {
                            //Returns a result if an IOException was thrown.
                            return "got IOException, as expected";
                        } else //Otherwise rethrow the exception.
                            throw _exception;
                    }
                });

                //Create an exception request and doSend it to the exception blade for processing.
                //The thrown exception is then caught by the assigned exception handler.
                _asyncRequestImpl.send(exceptionBlade.exceptionAOp(), new AsyncResponseProcessor&lt;Void&gt;() {
                    @Override
                    public void processAsyncResponse(final Void _response) throws Exception {
                        _asyncResponseProcessor.processAsyncResponse("can not get here");
                    }
                });
            }
        };
    }
}

Output:

got first IOException, as expected
got IOException, as expected
</pre>
</body>
</html>
